package io.agora.agora_rtc_engine_example

import android.os.Bundle
import io.agora.agora_rtc_engine_example.custom_capture_audio.CustomCaptureAudio
import io.agora.agora_rtc_engine_example.custom_capture_audio.CustomCaptureAudioPlugin
import io.agora.agora_rtc_engine_example.deepar_video.CustomCaptureVideo
//import io.agora.agora_rtc_engine_example.deepar_video.CustomCaptureVideoPlugin
import io.agora.rtc.base.RtcEnginePlugin
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant
import java.lang.ref.WeakReference


class MainActivity: FlutterActivity() {

  private val customCaptureAudioPlugin = CustomCaptureAudioPlugin(WeakReference(this))
//  private val customCaptureVideoPlugin = CustomCaptureVideoPlugin(WeakReference(this),lifecycle)

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    // Register the `CustomCaptureAudioPlugin` to interect with the `RtcEngine`
    RtcEnginePlugin.register(customCaptureAudioPlugin)
//    RtcEnginePlugin.register(customCaptureVideoPlugin)

  }

  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    // The `CustomCaptureAudioPlugin` is generated by [pigeon](https://pub.dev/packages/pigeon), you can see the
    // the definiton on `example/lib/examples/advanced/custom_audio/custom_audio_source_api.dart`
    CustomCaptureAudio.CustomCaptureAudioApi.setup(flutterEngine.dartExecutor, customCaptureAudioPlugin)
//    CustomCaptureVideo.CustomCaptureVideoApi.setup(flutterEngine.dartExecutor, customCaptureVideoPlugin)
//    GeneratedPluginRegistrant.registerWith(flutterEngine)
//    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "plugins.flutter.io/deep_ar_camera")
//    CameraDeepArPlugin.registerWith(flutterEngine.registrarFor("plugins.flutter.io/deep_ar_camera"))
  }

  override fun onDestroy() {
    super.onDestroy()

    RtcEnginePlugin.unregister(customCaptureAudioPlugin)
//    RtcEnginePlugin.unregister(customCaptureVideoPlugin)
  }
}
