// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by CustomCaptureVideoApi.
NSObject<FlutterMessageCodec> *CustomCaptureVideoApiGetCodec(void);

@protocol CustomCaptureVideoApi
/// @return `nil` only when `error != nil`.
- (void)setExternalVideoSourceEnabled:(NSNumber *)enabled useTexture:(NSNumber *)useTexture pushMmode:(NSNumber *)pushMmode error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (void)startRendererWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (void)stoRendererWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CustomCaptureVideoApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CustomCaptureVideoApi> *_Nullable api);

NS_ASSUME_NONNULL_END
