// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "CustomCaptureVideoApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface CustomCaptureVideoApiCodecReader : FlutterStandardReader
@end
@implementation CustomCaptureVideoApiCodecReader
@end

@interface CustomCaptureVideoApiCodecWriter : FlutterStandardWriter
@end
@implementation CustomCaptureVideoApiCodecWriter
@end

@interface CustomCaptureVideoApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation CustomCaptureVideoApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[CustomCaptureVideoApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[CustomCaptureVideoApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *CustomCaptureVideoApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    CustomCaptureVideoApiCodecReaderWriter *readerWriter = [[CustomCaptureVideoApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void CustomCaptureVideoApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CustomCaptureVideoApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CustomCaptureVideoApi.setExternalVideoSource"
        binaryMessenger:binaryMessenger
        codec:CustomCaptureVideoApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setExternalVideoSourceEnabled:useTexture:pushMmode:error:)], @"CustomCaptureVideoApi api (%@) doesn't respond to @selector(setExternalVideoSourceEnabled:useTexture:pushMmode:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_enabled = args[0];
        NSNumber *arg_useTexture = args[1];
        NSNumber *arg_pushMmode = args[2];
        FlutterError *error;
        [api setExternalVideoSourceEnabled:arg_enabled useTexture:arg_useTexture pushMmode:arg_pushMmode error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CustomCaptureVideoApi.startRenderer"
        binaryMessenger:binaryMessenger
        codec:CustomCaptureVideoApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startRendererWithError:)], @"CustomCaptureVideoApi api (%@) doesn't respond to @selector(startRendererWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startRendererWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CustomCaptureVideoApi.stoRenderer"
        binaryMessenger:binaryMessenger
        codec:CustomCaptureVideoApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stoRendererWithError:)], @"CustomCaptureVideoApi api (%@) doesn't respond to @selector(stoRendererWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stoRendererWithError:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
